from io import BytesIO
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import PageBreak, Paragraph, SimpleDocTemplate, Spacer

from app.generation.industry_profiles import profile_label
from app.schemas.instruction import InstructionResponse, StepFrameLink


SERVICE_NAME = "Procedra"
WATERMARK_TEXT = "Generated by Procedra"
BRAND_WORDMARK_PNG = Path(__file__).resolve().parents[1] / "static" / "assets" / "brand" / "procedra-wordmark-monochrome.png"

FONT_CANDIDATES = [
    "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
    "/System/Library/Fonts/Supplemental/Arial.ttf",
    "/System/Library/Fonts/Supplemental/Arial Bold.ttf",
    "/Library/Fonts/Arial.ttf",
]


def render_instruction_pdf(payload: InstructionResponse) -> bytes:
    buffer = BytesIO()
    font_name, bold_font_name = _register_fonts()
    styles = _styles(font_name, bold_font_name)
    document = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=16 * mm,
        leftMargin=16 * mm,
        topMargin=16 * mm,
        bottomMargin=18 * mm,
        title=payload.instruction.title,
        author=SERVICE_NAME,
    )
    story = _build_story(payload, styles)
    document.build(
        story,
        onFirstPage=lambda canvas, doc: _decorate_page(canvas, doc, font_name),
        onLaterPages=lambda canvas, doc: _decorate_page(canvas, doc, font_name),
    )
    return buffer.getvalue()


def _register_fonts() -> tuple[str, str]:
    regular = next((Path(path) for path in FONT_CANDIDATES if Path(path).exists() and "Bold" not in path), None)
    bold = next((Path(path) for path in FONT_CANDIDATES if Path(path).exists() and "Bold" in path), None)
    if regular:
        pdfmetrics.registerFont(TTFont("InstructionSans", str(regular)))
        if bold:
            pdfmetrics.registerFont(TTFont("InstructionSans-Bold", str(bold)))
            return "InstructionSans", "InstructionSans-Bold"
        return "InstructionSans", "InstructionSans"
    return "Helvetica", "Helvetica-Bold"


def _styles(font_name: str, bold_font_name: str) -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle(
            "InstructionTitle",
            parent=base["Title"],
            fontName=bold_font_name,
            fontSize=17,
            leading=21,
            alignment=TA_CENTER,
            spaceAfter=8,
        ),
        "h2": ParagraphStyle(
            "InstructionHeading",
            parent=base["Heading2"],
            fontName=bold_font_name,
            fontSize=12,
            leading=15,
            textColor=colors.HexColor("#115e59"),
            spaceBefore=8,
            spaceAfter=5,
        ),
        "body": ParagraphStyle(
            "InstructionBody",
            parent=base["BodyText"],
            fontName=font_name,
            fontSize=9.5,
            leading=12.5,
            spaceAfter=4,
        ),
        "meta": ParagraphStyle(
            "InstructionMeta",
            parent=base["BodyText"],
            fontName=font_name,
            fontSize=8.5,
            leading=11,
            textColor=colors.HexColor("#66767d"),
            spaceAfter=3,
        ),
    }


def _build_story(payload: InstructionResponse, styles: dict[str, ParagraphStyle]) -> list:
    instruction = payload.instruction
    links_by_step = {link.step_number: link for link in payload.step_frame_links}
    story: list = [
        Paragraph(_escape(instruction.title), styles["title"]),
        Paragraph(f"Режим генерации: {_escape(payload.generation_mode)}", styles["meta"]),
        Paragraph(f"Оценка качества: {payload.evaluation.overall_score}/100. {_escape(payload.evaluation.verdict)}", styles["meta"]),
        Paragraph(f"Уровень риска: {_risk_label(payload.evaluation.risk_level)}", styles["meta"]),
        Spacer(1, 4),
    ]

    _section(story, styles, "Назначение", [instruction.purpose])
    _section(story, styles, "Область применения", [instruction.scope])
    _section(
        story,
        styles,
        "Паспорт инструкции",
        [
            f"Участок: {instruction.department or 'Не указано'}",
            f"Оборудование: {instruction.equipment or 'Не указано'}",
            f"Уровень пользователя: {instruction.operator_level}",
            f"Статус: {instruction.workflow.status_label}.",
        ],
    )
    _section(story, styles, "Роли для согласования", instruction.workflow.required_review_roles)
    _section(story, styles, "Блокеры перед утверждением", instruction.workflow.approval_blockers)
    _section(story, styles, "Следующие действия по внедрению", instruction.workflow.next_actions)
    _section(story, styles, "Матрица ответственности", _responsibility_items())
    _section(story, styles, "Утверждения из входных данных", instruction.observed_facts)
    _section(
        story,
        styles,
        "Происхождение и статус утверждений",
        [
            (
                f"[{claim.claim_id or 'claim_id отсутствует'}; {claim.provenance}; "
                f"{claim.validation_status}; source={claim.source_id or 'не указан'}] {claim.text}"
                + (
                    " | validated by "
                    f"{claim.validation_record.reviewer_name} "
                    f"({claim.validation_record.reviewer_role}); "
                    f"evidence={claim.validation_record.evidence_reference}"
                    if claim.validation_record
                    else ""
                )
            )
            for claim in instruction.evidence_claims
        ],
    )
    _section(story, styles, "Что требуется проверить локально", instruction.local_verification_required)
    _section(story, styles, "Вопросы для экспертной проверки", instruction.expert_review_questions)
    _section(story, styles, "Средства индивидуальной защиты", instruction.required_ppe)
    _section(story, styles, "Инструменты и документы", instruction.required_tools)
    _section(story, styles, "Требования безопасности", instruction.safety_requirements)
    _section(story, styles, "Опасные зоны", instruction.hazard_zones)
    _section(story, styles, "Предварительные условия", instruction.prerequisites)

    story.append(Paragraph("Порядок выполнения", styles["h2"]))
    for step in instruction.steps:
        story.append(Paragraph(f"{step.number}. {_escape(step.action)}", styles["body"]))
        _meta(story, styles, f"Ожидаемый результат: {step.expected_result}")
        if step.safety_note:
            _meta(story, styles, f"Безопасность: {step.safety_note}")
        if step.verification_method:
            _meta(story, styles, f"Проверка: {step.verification_method}")
        if step.common_mistakes:
            _meta(story, styles, f"Типовые ошибки: {', '.join(step.common_mistakes)}")
        if step.number in links_by_step:
            _step_link(story, styles, links_by_step[step.number])
        story.append(Spacer(1, 2))

    _section(story, styles, "Критерии приемки результата", _acceptance_items(instruction.control_points))
    _section(story, styles, "Чеклист качества", instruction.quality_checklist)
    _section(story, styles, "Действия при нештатной ситуации", instruction.emergency_actions)
    _section(story, styles, "Типовые ошибки", instruction.common_mistakes)
    _section(story, styles, "Экспертная проверка", _expert_review_items(payload))
    _section(story, styles, "Ограничения и проверка перед внедрением", _limitation_items())

    if payload.sources:
        story.append(PageBreak())
        story.append(Paragraph("Использованные источники", styles["h2"]))
        for source in payload.sources:
            story.append(Paragraph(_escape(source.title), styles["body"]))
            source_kind = "открытый интернет-источник" if source.source_type == "public" else "локальная база"
            source_location = source.url or source.path
            _meta(
                story,
                styles,
                (
                    f"Тип: {source_kind}. Источник: {source_location} #{source.chunk_index}; "
                    f"релевантность: {source.score:.3f}; влияние: {source.influence_score:.2f}"
                ),
            )
            if source.document_type or source.authority:
                _meta(
                    story,
                    styles,
                    f"Документ: {source.document_type or 'не указан'}; орган/площадка: {source.authority or 'не указано'}",
                )
            if source.applicable_profiles:
                profiles = ", ".join(profile_label(profile) for profile in source.applicable_profiles)
                _meta(story, styles, f"Профили применимости: {profiles}")
            if source.contribution_reason:
                _meta(story, styles, f"Почему выбран: {source.contribution_reason}")
            if source.matched_terms:
                _meta(story, styles, f"Совпавшие термины: {', '.join(source.matched_terms)}")
            _meta(story, styles, source.excerpt)

    return story


def _section(story: list, styles: dict[str, ParagraphStyle], title: str, items: list[str]) -> None:
    story.append(Paragraph(_escape(title), styles["h2"]))
    for item in items or ["Не указано"]:
        story.append(Paragraph(f"• {_escape(item)}", styles["body"]))


def _meta(story: list, styles: dict[str, ParagraphStyle], text: str) -> None:
    story.append(Paragraph(_escape(text), styles["meta"]))


def _step_link(story: list, styles: dict[str, ParagraphStyle], link: StepFrameLink) -> None:
    minutes = int(round(link.timestamp_seconds)) // 60
    seconds = int(round(link.timestamp_seconds)) % 60
    _meta(
        story,
        styles,
        f"Видео: {minutes:02d}:{seconds:02d}, кадр {link.frame_index}, уверенность {link.confidence:.2f}. {link.reason}",
    )


def _responsibility_items() -> list[str]:
    return [
        "Оператор выполняет действия только в пределах допуска и фиксирует отклонения.",
        "Мастер смены подтверждает применимость инструкции к конкретному участку и оборудованию.",
        "Инженер/технолог уточняет режимы, допуски и локальные требования, отсутствующие во входных данных.",
    ]


def _acceptance_items(control_points: list[str]) -> list[str]:
    return [
        "Все обязательные контрольные точки выполнены и подтверждены ответственным лицом.",
        "Рабочее место и оборудование находятся в безопасном, определенном состоянии.",
        "Отклонения, замечания и ограничения зафиксированы в принятой на участке форме.",
        *control_points,
    ]


def _limitation_items() -> list[str]:
    return [
        "Документ является AI-черновиком и не заменяет утвержденные инструкции предприятия.",
        "Точные режимы, нормы времени, допуски и ссылки на стандарты должны быть подтверждены локальной документацией.",
        "Перед применением на производстве инструкцию должен проверить ответственный специалист по технологии и охране труда.",
    ]


def _expert_review_items(payload: InstructionResponse) -> list[str]:
    review_status = "требуется" if payload.evaluation.expert_review_required else "не требуется"
    return [
        f"Статус экспертной проверки: {review_status}.",
        f"Уровень риска: {_risk_label(payload.evaluation.risk_level)}.",
        *payload.evaluation.expert_review_notes,
    ]


def _risk_label(risk_level: str) -> str:
    labels = {
        "low": "низкий",
        "medium": "средний",
        "high": "высокий",
        "critical": "критический",
    }
    return labels.get(risk_level, risk_level)


def _decorate_page(canvas, document, font_name: str) -> None:
    width, height = A4
    canvas.saveState()
    canvas.setFont(font_name, 34)
    canvas.setFillColor(colors.Color(0.08, 0.46, 0.43, alpha=0.08))
    canvas.translate(width / 2, height / 2)
    canvas.rotate(34)
    canvas.drawCentredString(0, 0, WATERMARK_TEXT)
    canvas.restoreState()

    canvas.saveState()
    if BRAND_WORDMARK_PNG.is_file():
        canvas.drawImage(
            str(BRAND_WORDMARK_PNG),
            document.leftMargin,
            7.7 * mm,
            width=25 * mm,
            height=4.7 * mm,
            preserveAspectRatio=True,
            anchor="sw",
            mask="auto",
        )
    else:
        canvas.setFont(font_name, 8)
        canvas.setFillColor(colors.HexColor("#66767d"))
        canvas.drawString(document.leftMargin, 10 * mm, SERVICE_NAME)
    canvas.setFont(font_name, 8)
    canvas.setFillColor(colors.HexColor("#66767d"))
    canvas.drawRightString(width - document.rightMargin, 10 * mm, f"Страница {document.page}")
    canvas.restoreState()


def _escape(value: object) -> str:
    return (
        str(value)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )
